##################
# --- Header --- #
##################

title: Erring Less

author: Jan-Michael Cabrera

################################
# --- Navigation Bar Links --- #
################################

navbar-links:
  About Me: 'about'

################
# --- Logo --- #
################

# avatar: '/assets/'

#####################################
# --- Footer social media links --- #
#####################################

description: >-
  A blog to write down notes for my future self exploring some ideas in maths, science, and learning algorithms.
baseurl: ""
url: ""

email: janmichael.cabrera@gmail.com
twitter_username: jan_cabrera
github_username:  buns

##########################
# --- Build Settings --- #
##########################

theme: minima
plugins:
  - jekyll-feed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/